apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: proactive
  name: proactive-node
spec:
  maxReplicas: 4
  minReplicas: 1
  scaleTargetRef:
    apiVersion: v1
    kind: DeploymentConfig
    name: proactive-node
  targetCPUUtilizationPercentage: 50